version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-aplicacion
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mi-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: mi_base_datos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"

volumes:
  db_data:
